spin_manifest_version = 2

[application]
authors = ["Fermyon"]
description = "Shows how to parse an HTTP request cookie"
name = "parse-cookie"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "parse-cookie"

[component.parse-cookie]
source = "dist/parse-cookie.wasm"
exclude_files = ["**/node_modules"]
[component.parse-cookie.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]