spin_manifest_version = 2

[application]
name = "geoip-example"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "geoip-example"

[component.geoip-example]
source = "target/wasm32-wasip1/release/geoip_example.wasm"
allowed_outbound_hosts = []
[component.geoip-example.build]
command = "make build"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.geoip-example.dependencies]
"fermyon:geoip/lookup" = { path = "geoip-static-db/target/geoip_initialized.wasm" }
