spin_manifest_version = 2

[application]
name = "ab-testing-kv"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "traffic-router"

[[trigger.http]]
route = "/origin-a/..."
component = "origin-a"

[[trigger.http]]
route = "/origin-b/..."
component = "origin-b"

[component.traffic-router]
source = "traffic-router/target/wasm32-wasip1/release/traffic_router.wasm"
allowed_outbound_hosts = ["http://self", "https://self"]
key_value_stores = ["default"]

[component.traffic-router.build]
workdir = "traffic-router"
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.origin-a]
source = "origin-a/target/wasm32-wasip1/release/origin_a.wasm"
allowed_outbound_hosts = []

[component.origin-a.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "origin-a"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.origin-b]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets-b", destination = "/" }]
environment = { CACHE_CONTROL = "no-cache" }
