[package]
name = "rules-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.4", features = ["derive"] }
fcsd.workspace = true
fst.workspace = true
url = "2.5.4"

[dev-dependencies]
tempfile = "3.19.1"
