spin_manifest_version = 2

[application]
name = "shirt-shop"
version = "0.1.0"
authors = ["Fermyon"]
description = "A sample backend for testing/demoing the rewriter"

[[trigger.http]]
route = "/..."
component = "shirt-shop"

[component.shirt-shop]
source = { url = "https://github.com/spinframework/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]
