spin_manifest_version = 2

[application]
name = "todomvc"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "frontend"

[[trigger.http]]
route = "/api/..."
component = "api"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "frontend/dist", destination = "/" }]
environment = { FALLBACK_PATH = "index.html" }

[component.frontend.build]
command = "npm install && npm run build"
workdir = "frontend"


[component.api]
source = "api/main.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.api.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
workdir = "api"
watch = ["**/*.go", "go.mod"]
