spin_manifest_version = 2

[application]
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = "Read data from a POST request"
name = "read-post"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "read-post"

[component.read-post]
source = "dist/read-post.wasm"
exclude_files = ["**/node_modules"]
[component.read-post.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]