spin_manifest_version = 2

[application]
authors = ["Adam Reese <adam@reese.io>"]
description = ""
name = "fetch-json"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "fetch-json"

[component.fetch-json]
source = "dist/fetch-json.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://random-data-api.fermyon.app/"]
[component.fetch-json.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
