spin_manifest_version = 2

[application]
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""
name = "stream-data-from-linode-object-store-tutorial"
version = "0.1.0"

[variables]
region = { required = true }
endpoint = { required = true }
bucket_name = { required = true }
access_key_id = { required = true }
secret_access_key = { required = true, secret = true }

[[trigger.http]]
route = "/..."
component = "stream-data-from-linode-object-store-tutorial"

[component.stream-data-from-linode-object-store-tutorial]
source = "dist/stream-data-from-linode-object-store-tutorial.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ['https://{{ bucket_name }}.{{ endpoint }}']

[component.stream-data-from-linode-object-store-tutorial.variables]
region = "{{ region }}"
endpoint = "https://{{ endpoint }}"
bucket_name = "{{ bucket_name }}"
access_key_id = "{{ access_key_id }}"
secret_access_key = "{{ secret_access_key }}"

[component.stream-data-from-linode-object-store-tutorial.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]

