spin_manifest_version = 2

[application]
name = "early-hints-rust"
version = "0.1.0"

[variables]
harper_url = { required = true }
harper_auth_header = { required = true }

[[trigger.http]]
route = "/..."
component = "early-rs"

[component.early-rs]
source = "target/wasm32-wasip1/release/early_rs.wasm"
allowed_outbound_hosts = ["{{ harper_url }}"]
[component.early-rs.variables]
harper_url = "{{ harper_url }}"
harper_auth_header = "{{ harper_auth_header }}"
[component.early-rs.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
