spin_manifest_version = 2

[application]
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""
name = "hello-postgresql"
version = "0.1.0"

[variables]
pg_connection_string = { required = true }

[[trigger.http]]
route = "/..."
component = "hello-postgresql"

[component.hello-postgresql]
source = "dist/hello-postgresql.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = [
  "postgres://ep-red-mouse-a2flzxns.eu-central-1.aws.neon.tech:5432",
]

[component.hello-postgresql.variables]
pg_connection_string = "{{ pg_connection_string }}"

[component.hello-postgresql.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.js", "package.json"]
