spin_manifest_version = 2

[application]
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""
name = "block-by-ip"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "block-by-ip"

[component.block-by-ip]
source = "dist/block-by-ip.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]

[component.block-by-ip.build]
command = "npm install && npm run build"
watch = ["src/**/*.js", "package.json"]
