spin_manifest_version = 2

[application]
description = "Redirect requests to certain URLs based on a mapped object to the request's URL."
name = "bulk-redirects"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "bulk-redirects"

[component.bulk-redirects]
source = "dist/bulk-redirects.wasm"
exclude_files = ["**/node_modules"]
[component.bulk-redirects.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]