spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "block-by-country"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "block-by-country"

[component.block-by-country]
source = "dist/block-by-country.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
allowed_outbound_hosts = ["http://ip-api.com"]
[component.block-by-country.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.js"]
